library(mosaic)
library(manipulate)


mPlot(CO2)
View(CO2)
plot(uptake ~ conc, data=CO2)

mPlot(CO2)
mPlot(subset(CO2, conc>250))
plot(uptake ~ conc, data=subset(CO2, conc > 250), col=interaction(Type,Treatment))
plot(uptake ~ conc, data=subset(CO2, conc > 250), col=Type)
plot(uptake ~ conc, data=subset(CO2, conc > 250), col=Treatment)
plot(uptake ~ conc, data=subset(CO2, conc > 250))
lm.x2 <- lm(uptake ~ conc + Treatment, data=subset(CO2, conc > 250))
abline(lm.x2)
lm.x2$coefficients
plot(uptake ~ conc, data=subset(CO2, conc > 250))
lm.x2 <- lm(uptake ~ conc + Treatment, data=subset(CO2, conc > 250))
lm.x2$coefficients
summary(lm.x2)
b <- lm.x2$coefficients
abline(b[1],b[2])
abline(b[1]+b[3], b[2])
plot(uptake ~ conc, data=subset(CO2, conc > 250), col=Treatment)
abline(b[1],b[2], col="black")
abline(b[1]+b[3], b[2], col="red")
plot(lm.x2, which=1)
plot(lm.x2, which=2)
lm.x2x1 <- lm(uptake ~ conc + Treatment + conc:Treatment, data=subset(CO2, conc > 250))
summary(lm.x2x1)
str(CO2)
summary(lm.x2x1)
plot(uptake ~ conc, data=subset(CO2, conc > 250), col=Treatment)
plot(uptake ~ conc, data=subset(CO2, conc > 250))
b <- coef(lm.x2x1)
abline(b[1],b[2])
abline(b[1]+b[3], b[2]+b[4])
lm.x2x3 <- lm(uptake ~ conc + Treatment + conc:Treatment + Type + conc:Type, data=subset(CO2, conc > 250))
summary(lm.x2x3)
plot(uptake ~ conc, data=subset(CO2, conc > 250))
b <- coef(lm.x2x3)
abline(b[1],b[2])
abline(b[1]+b[3], b[2])